"""Merge-ready output for a verified finding: a pull-request write-up and a
single patch file that carries both the source fix and the new regression
test. Everything a reviewer needs to approve the change in one place."""
from __future__ import annotations

import difflib
import os
from typing import Dict, Optional

from . import util

_PR_MD = """# Fix {cwe} {cwe_name} in `{func}` ({task})

**Severity:** {severity}  ·  **Finding:** `{fid}`  ·  **Signature:** `{sig}`

## Summary
A reproducible {asan_class} was found in `{crash_file}` (`{func}`) by KavachForge's
hybrid discovery (structure-aware seeds + fuzzing under AddressSanitizer). This PR adds a
minimal guard at the root cause and a regression test generated from the exact
proof-of-vulnerability input.

{rationale}

## Evidence
- Proof-of-vulnerability: `{pov_file}` ({pov_size} bytes, sha256 `{pov_sha}`)
- Reproduce (unpatched): `{repro}`
- Sanitizer class: `{asan_class}` · access: {access}
- Duplicate crashes collapsed into this finding: {dups}

## Verification (all gates must pass)
{gates}

## Changes
- `{rel_path}` — root-cause guard ({added} line(s) added)
- `{test_path}` — new regression test from the PoV ({test_proof})

## Review notes
- Only `{rel_path}` is modified; no tests, harness or build flags were touched (enforced by policy).
- The original behaviour for valid inputs is unchanged (existing regression suite passes).
- Human review and approval required before merge; KavachForge does not deploy.

<sub>Generated by KavachForge {version}. Patch applies with `patch -p1 < fix.patch` from the target root.</sub>
"""


def _new_file_diff(rel_path: str, content: str) -> str:
    lines = content.splitlines(keepends=True)
    return "".join(difflib.unified_diff(
        [], lines, fromfile="/dev/null", tofile="b/" + rel_path, n=0))


def build(task, finding, patch_entry: Dict, validation: Dict,
          regress_src: Optional[str], work_dir: str, version: str) -> Dict[str, str]:
    fid = finding.id
    out = os.path.join(work_dir, "pr", fid)
    os.makedirs(out, exist_ok=True)

    # One patch: the fix, plus the regression test as a new file.
    full = patch_entry.get("diff", "")
    rt = validation.get("regression_test") or {}
    test_rel = rt.get("rel_test_path", "")
    if regress_src and os.path.exists(regress_src) and test_rel:
        full = full.rstrip("\n") + "\n" + _new_file_diff(test_rel, util.read_text(regress_src))
    patch_path = os.path.join(out, "fix.patch")
    util.write_text(patch_path, full)

    gates_md = "\n".join(
        "- [%s] **%s** — %s" % ("x" if g["passed"] else " ", g["name"], g["detail"])
        for g in validation.get("gates", []))
    added = sum(1 for l in patch_entry.get("diff", "").splitlines()
                if l.startswith("+") and not l.startswith("+++"))
    test_proof = ("proven: crashes unpatched, passes patched"
                  if rt.get("guards_bug") else "generated; see G4 gate")

    md = _PR_MD.format(
        cwe=finding.cwe, cwe_name=finding.cwe_name, func=finding.crash_func,
        task=task.name, severity=finding.severity, fid=fid, sig=finding.signature,
        asan_class=finding.asan_class, crash_file=finding.crash_file,
        rationale=patch_entry.get("rationale", ""),
        pov_file=os.path.basename(finding.pov_path), pov_size=finding.pov_size,
        pov_sha=finding.pov_sha256[:16], repro=finding.repro_cmd,
        access=finding.access, dups=finding.duplicates, gates=gates_md,
        rel_path=patch_entry.get("rel_path", ""), added=added,
        test_path=test_rel or "(none)", test_proof=test_proof, version=version)
    md_path = os.path.join(out, "PR.md")
    util.write_text(md_path, md)
    return {"dir": os.path.relpath(out, work_dir),
            "patch": os.path.relpath(patch_path, work_dir),
            "md": os.path.relpath(md_path, work_dir)}
